language: python
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION=1.4.10
python:
  - "2.7"
  - "3.3"
env:
    - DJANGO='Django==1.6'
    - DJANGO='https://github.com/django/django/archive/1.7c1.zip'
install:
    - pip install -q nose django-nose $DJANGO
    - pip install .

script: ./runtests.py
